import { NextResponse } from "next/server";
import dbConnect from "@/lib/db";
import State from "@/models/State";
import City from "@/models/City";
import TouristPlace from "@/models/TouristPlace";
import AdminUser from "@/models/AdminUser";
import bcrypt from "bcryptjs";

const statesData = [
  { name: "Rajasthan", slug: "rajasthan", capital: "Jaipur", bestSeason: "October to March (Winter)", featured: true, image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800", description: "Rajasthan, the Land of Kings, is India's largest state by area. Known for its magnificent forts, opulent palaces, vibrant culture, and the vast Thar Desert. The state offers a kaleidoscope of experiences from the pink city of Jaipur to the blue city of Jodhpur.", quickFacts: ["Largest state by area", "Known as Land of Kings", "Home to Thar Desert", "Famous for Rajputana architecture"] },
  { name: "Kerala", slug: "kerala", capital: "Thiruvananthapuram", bestSeason: "September to March", featured: true, image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800", description: "Kerala, God's Own Country, is a tropical paradise on India's southwestern coast. Famous for its backwaters, lush hill stations, pristine beaches, and rich Ayurvedic heritage. The state boasts incredible biodiversity and unique cultural traditions.", quickFacts: ["Known as God's Own Country", "Famous for backwaters", "Highest literacy rate in India", "Major Ayurveda hub"] },
  { name: "Goa", slug: "goa", capital: "Panaji", bestSeason: "November to February", featured: true, image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800", description: "Goa is India's smallest state and a beloved beach destination. Known for its stunning coastline, Portuguese heritage, vibrant nightlife, and laid-back atmosphere. From historic churches to golden beaches, Goa offers something for everyone.", quickFacts: ["Smallest state in India", "Portuguese colonial heritage", "Famous for beaches and nightlife", "Home to UNESCO World Heritage churches"] },
  { name: "Himachal Pradesh", slug: "himachal-pradesh", capital: "Shimla", bestSeason: "March to June, September to November", featured: true, image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800", description: "Himachal Pradesh, the Land of Gods, is a northern Indian state in the western Himalayas. Known for its stunning mountain landscapes, adventure sports, ancient temples, and charming hill stations like Shimla and Manali.", quickFacts: ["Known as Dev Bhoomi (Land of Gods)", "Capital shifts between Shimla and Dharamshala", "Home to Dalai Lama in Dharamshala", "Famous for apple orchards"] },
  { name: "Uttar Pradesh", slug: "uttar-pradesh", capital: "Lucknow", bestSeason: "October to March", featured: true, image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800", description: "Uttar Pradesh is India's most populous state and a treasure trove of history and culture. Home to the iconic Taj Mahal, the sacred city of Varanasi, and the birthplace of Lord Rama in Ayodhya, UP is central to India's spiritual and cultural identity.", quickFacts: ["Most populous state in India", "Home to the Taj Mahal", "Sacred city of Varanasi on the Ganges", "Rich Mughal and Awadhi heritage"] },
  { name: "Delhi", slug: "delhi", capital: "New Delhi", bestSeason: "October to March", featured: true, image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800", description: "Delhi, India's capital territory, is a city where ancient history meets modern ambition. From the Mughal-era Red Fort and Humayun's Tomb to the modern Lotus Temple and India Gate, Delhi offers an extraordinary blend of the old and new.", quickFacts: ["Capital of India", "Home to UNESCO World Heritage Sites", "Blend of Mughal and modern architecture", "Major cultural and political hub"] },
  { name: "Uttarakhand", slug: "uttarakhand", capital: "Dehradun", bestSeason: "March to June, September to November", featured: true, image: "https://images.unsplash.com/photo-1580289884710-1067cf41a08c?w=800", description: "Uttarakhand, the Land of Gods, lies in the lap of the Himalayas. Known for its sacred pilgrimage sites, stunning hill stations, wildlife sanctuaries, and adventure sports. From the spiritual Char Dham to the adventure capital Rishikesh.", quickFacts: ["Known as Devbhumi", "Home to Char Dham pilgrimage", "Yoga capital of the world (Rishikesh)", "Rich biodiversity with Jim Corbett National Park"] },
  { name: "Maharashtra", slug: "maharashtra", capital: "Mumbai", bestSeason: "October to March", featured: true, image: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800", description: "Maharashtra is India's third-largest state and economic powerhouse. Home to Mumbai, the city of dreams, and ancient cave temples of Ajanta and Ellora. The state offers diverse experiences from bustling cities to serene hill stations.", quickFacts: ["Financial capital of India (Mumbai)", "Home to Bollywood", "Ajanta & Ellora cave temples", "Rich Maratha heritage"] },
  { name: "Tamil Nadu", slug: "tamil-nadu", capital: "Chennai", bestSeason: "November to February", featured: false, image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800", description: "Tamil Nadu is a land of temples, traditions, and timeless culture. Home to some of India's most magnificent Dravidian temples, pristine beaches, and the lush Nilgiri Hills. The state preserves one of the world's oldest living civilizations.", quickFacts: ["Dravidian temple architecture", "Home to classical Bharatanatyam dance", "UNESCO heritage Chola temples", "Famous for filter coffee and cuisine"] },
  { name: "Jammu & Kashmir", slug: "jammu-kashmir", capital: "Srinagar", bestSeason: "April to October", featured: false, image: "https://images.unsplash.com/photo-1597074866923-dc0589150a32?w=800", description: "Jammu & Kashmir, often called Paradise on Earth, is renowned for its breathtaking natural beauty. From the serene Dal Lake to snow-capped peaks, lush valleys, and Mughal gardens, the region offers unparalleled scenic splendor.", quickFacts: ["Known as Paradise on Earth", "Famous for Dal Lake houseboats", "Mughal Gardens heritage", "World-class skiing in Gulmarg"] },
];

export async function POST() {
  try {
    await dbConnect();
    // Clear existing
    await Promise.all([State.deleteMany({}), City.deleteMany({}), TouristPlace.deleteMany({}), AdminUser.deleteMany({})]);
    // Create admin
    const hashedPw = await bcrypt.hash(process.env.ADMIN_PASSWORD || "Admin@123", 12);
    await AdminUser.create({ email: process.env.ADMIN_EMAIL || "admin@travelbharat.com", password: hashedPw, name: "Admin", role: "admin" });
    // Create states
    const createdStates = await State.insertMany(statesData);
    const stateMap: Record<string, string> = {};
    createdStates.forEach((s) => { stateMap[s.slug] = s._id.toString(); });

    // Cities
    const citiesData = [
      { name: "Jaipur", slug: "jaipur", stateId: stateMap["rajasthan"], image: "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?w=800", description: "The Pink City of India, Jaipur is the capital of Rajasthan and a UNESCO World Heritage Site. Known for its stunning forts, palaces, and vibrant bazaars.", bestTime: "October to March" },
      { name: "Udaipur", slug: "udaipur", stateId: stateMap["rajasthan"], image: "https://images.unsplash.com/photo-1602508451748-cb083ac3f5d4?w=800", description: "The City of Lakes, Udaipur is one of India's most romantic cities with stunning palatial architecture set against the backdrop of the Aravalli Hills.", bestTime: "September to March" },
      { name: "Kochi", slug: "kochi", stateId: stateMap["kerala"], image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800", description: "Queen of the Arabian Sea, Kochi is a vibrant port city with a rich history shaped by Arab, Chinese, Dutch, and Portuguese influences.", bestTime: "September to March" },
      { name: "Munnar", slug: "munnar", stateId: stateMap["kerala"], image: "https://images.unsplash.com/photo-1611258800813-76a08e111500?w=800", description: "A hill station in Kerala's Western Ghats, Munnar is famous for its rolling tea plantations, misty peaks, and diverse wildlife.", bestTime: "September to May" },
      { name: "Panaji", slug: "panaji", stateId: stateMap["goa"], image: "https://images.unsplash.com/photo-1587922546307-776227941871?w=800", description: "The charming capital of Goa, Panaji features colorful Portuguese-era buildings, riverside promenades, and a relaxed atmosphere.", bestTime: "November to February" },
      { name: "Shimla", slug: "shimla", stateId: stateMap["himachal-pradesh"], image: "https://images.unsplash.com/photo-1597074866923-dc0589150a32?w=800", description: "The Queen of Hills, Shimla is Himachal Pradesh's capital, known for its colonial architecture, scenic beauty, and the famous Mall Road.", bestTime: "March to June" },
      { name: "Manali", slug: "manali", stateId: stateMap["himachal-pradesh"], image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800", description: "A popular hill station in Himachal Pradesh, Manali is a gateway to adventure sports and the stunning Rohtang Pass.", bestTime: "October to June" },
      { name: "Agra", slug: "agra", stateId: stateMap["uttar-pradesh"], image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800", description: "Home to the iconic Taj Mahal, Agra is a city steeped in Mughal history with magnificent architectural wonders.", bestTime: "October to March" },
      { name: "Varanasi", slug: "varanasi", stateId: stateMap["uttar-pradesh"], image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800", description: "One of the world's oldest continuously inhabited cities, Varanasi is the spiritual capital of India, sitting on the banks of the sacred Ganges.", bestTime: "October to March" },
      { name: "New Delhi", slug: "new-delhi", stateId: stateMap["delhi"], image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800", description: "India's capital city, New Delhi is a blend of historical monuments, government buildings, and modern urban development.", bestTime: "October to March" },
      { name: "Rishikesh", slug: "rishikesh", stateId: stateMap["uttarakhand"], image: "https://images.unsplash.com/photo-1588083949404-c4f1ed1323b3?w=800", description: "The Yoga Capital of the World, Rishikesh sits on the banks of the Ganges and is a hub for yoga, meditation, and adventure sports.", bestTime: "September to November, February to May" },
      { name: "Mumbai", slug: "mumbai", stateId: stateMap["maharashtra"], image: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800", description: "The City of Dreams, Mumbai is India's financial capital and home to Bollywood, iconic landmarks, and a vibrant street food culture.", bestTime: "November to February" },
      { name: "Chennai", slug: "chennai", stateId: stateMap["tamil-nadu"], image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800", description: "The Gateway to South India, Chennai is a cultural hub known for its temples, classical arts, and beautiful Marina Beach.", bestTime: "November to February" },
      { name: "Srinagar", slug: "srinagar", stateId: stateMap["jammu-kashmir"], image: "https://images.unsplash.com/photo-1597074866923-dc0589150a32?w=800", description: "The summer capital of J&K, Srinagar is famous for its Dal Lake houseboats, Mughal Gardens, and stunning Himalayan backdrop.", bestTime: "April to October" },
    ];
    const createdCities = await City.insertMany(citiesData);
    const cityMap: Record<string, string> = {};
    createdCities.forEach((c) => { cityMap[c.slug] = c._id.toString(); });

    // Places
    const placesData = [
      { name: "Hawa Mahal", slug: "hawa-mahal", stateId: stateMap["rajasthan"], cityId: cityMap["jaipur"], category: "heritage", featured: true, images: ["https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?w=800", "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800"], description: "The Palace of Winds, Hawa Mahal is an iconic pink sandstone structure with 953 small windows designed for royal women to observe street life.", history: "Built in 1799 by Maharaja Sawai Pratap Singh, inspired by the crown of Lord Krishna.", bestTime: "October to March", fees: "₹50 (Indians), ₹200 (Foreigners)", timings: "9:00 AM – 5:00 PM", mapLink: "https://maps.google.com/?q=Hawa+Mahal+Jaipur", nearbyAttractions: ["City Palace", "Jantar Mantar", "Nahargarh Fort"], tips: ["Visit early morning for best photos", "Explore the rooftop for panoramic views"], tags: ["popular", "family-friendly"] },
      { name: "Taj Mahal", slug: "taj-mahal", stateId: stateMap["uttar-pradesh"], cityId: cityMap["agra"], category: "heritage", featured: true, images: ["https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800", "https://images.unsplash.com/photo-1548013146-72479768bada?w=800"], description: "The Taj Mahal is an ivory-white marble mausoleum and one of the New Seven Wonders of the World. A UNESCO World Heritage Site and symbol of eternal love.", history: "Built between 1632-1653 by Mughal Emperor Shah Jahan in memory of his wife Mumtaz Mahal.", bestTime: "October to March", fees: "₹50 (Indians), ₹1300 (Foreigners)", timings: "6:00 AM – 6:30 PM (Closed on Fridays)", mapLink: "https://maps.google.com/?q=Taj+Mahal+Agra", nearbyAttractions: ["Agra Fort", "Mehtab Bagh", "Fatehpur Sikri"], tips: ["Visit at sunrise for the best experience", "Book tickets online to avoid queues", "Friday is closed for visitors"], tags: ["popular", "family-friendly"] },
      { name: "Kerala Backwaters", slug: "kerala-backwaters", stateId: stateMap["kerala"], cityId: cityMap["kochi"], category: "nature", featured: true, images: ["https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800"], description: "The Kerala Backwaters are a network of interconnected canals, rivers, and lakes stretching parallel to the Arabian Sea coast. A houseboat cruise is a must-do.", history: "These waterways have been vital trade routes for centuries, connecting the interior with the coast.", bestTime: "September to March", fees: "Houseboat from ₹5000/day", timings: "Open 24 hours", mapLink: "https://maps.google.com/?q=Alleppey+Backwaters", nearbyAttractions: ["Alleppey Beach", "Kumarakom Bird Sanctuary"], tips: ["Book houseboats in advance during peak season", "Carry mosquito repellent"], tags: ["popular", "family-friendly"] },
      { name: "Gateway of India", slug: "gateway-of-india", stateId: stateMap["maharashtra"], cityId: cityMap["mumbai"], category: "heritage", featured: true, images: ["https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800"], description: "The Gateway of India is an arch-monument built in the 20th century, overlooking the Arabian Sea. It is Mumbai's most iconic landmark.", history: "Built to commemorate the visit of King George V and Queen Mary in 1911, completed in 1924.", bestTime: "November to February", fees: "Free", timings: "Open 24 hours", mapLink: "https://maps.google.com/?q=Gateway+of+India+Mumbai", nearbyAttractions: ["Taj Mahal Palace Hotel", "Elephanta Caves", "Marine Drive"], tips: ["Visit early morning to avoid crowds", "Take a ferry to Elephanta Caves from here"], tags: ["popular", "family-friendly", "free-entry"] },
      { name: "Varanasi Ghats", slug: "varanasi-ghats", stateId: stateMap["uttar-pradesh"], cityId: cityMap["varanasi"], category: "religious", featured: true, images: ["https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800"], description: "The Ghats of Varanasi are a series of steps leading down to the banks of the Ganges River. The evening Ganga Aarti at Dashashwamedh Ghat is a mesmerizing spiritual experience.", history: "Varanasi is one of the oldest cities in the world, with ghats dating back thousands of years.", bestTime: "October to March", fees: "Free", timings: "Open 24 hours, Aarti at 6:30 PM", mapLink: "https://maps.google.com/?q=Dashashwamedh+Ghat+Varanasi", nearbyAttractions: ["Kashi Vishwanath Temple", "Sarnath", "Assi Ghat"], tips: ["Attend the Ganga Aarti at sunset", "Take a sunrise boat ride on the Ganges"], tags: ["popular", "free-entry"] },
      { name: "India Gate", slug: "india-gate", stateId: stateMap["delhi"], cityId: cityMap["new-delhi"], category: "heritage", featured: true, images: ["https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800"], description: "India Gate is a war memorial located along the Rajpath, now Kartavya Path. It commemorates Indian soldiers who died in World War I.", history: "Designed by Edwin Lutyens, completed in 1931. Names of 13,300 soldiers are inscribed on its walls.", bestTime: "October to March", fees: "Free", timings: "Open 24 hours", mapLink: "https://maps.google.com/?q=India+Gate+Delhi", nearbyAttractions: ["Rashtrapati Bhavan", "National Museum", "Humayun's Tomb"], tips: ["Visit in the evening for beautifully lit views", "Great for evening walks and street food"], tags: ["popular", "family-friendly", "free-entry"] },
      { name: "Laxman Jhula", slug: "laxman-jhula", stateId: stateMap["uttarakhand"], cityId: cityMap["rishikesh"], category: "adventure", featured: false, images: ["https://images.unsplash.com/photo-1588083949404-c4f1ed1323b3?w=800"], description: "Laxman Jhula is an iconic iron suspension bridge across the Ganges in Rishikesh. The area is a hub for yoga, rafting, and spiritual seekers.", history: "Legend says Lord Laxman crossed the Ganges here using a jute rope bridge.", bestTime: "September to November", fees: "Free", timings: "Open 24 hours", mapLink: "https://maps.google.com/?q=Laxman+Jhula+Rishikesh", nearbyAttractions: ["Ram Jhula", "Beatles Ashram", "Triveni Ghat"], tips: ["Try white water rafting on the Ganges", "Visit nearby ashrams for yoga sessions"], tags: ["adventure", "free-entry"] },
      { name: "Munnar Tea Gardens", slug: "munnar-tea-gardens", stateId: stateMap["kerala"], cityId: cityMap["munnar"], category: "nature", featured: false, images: ["https://images.unsplash.com/photo-1611258800813-76a08111e500?w=800"], description: "Munnar's rolling tea plantations are a visual treat, covering hills in lush green carpets. Visit the Tea Museum to learn about tea processing.", bestTime: "September to May", fees: "₹75 (Tea Museum)", timings: "9:00 AM – 4:00 PM", mapLink: "https://maps.google.com/?q=Munnar+Tea+Gardens", nearbyAttractions: ["Eravikulam National Park", "Top Station", "Mattupetty Dam"], tips: ["Carry warm clothes even in summer", "Best views during early morning"], tags: ["nature", "family-friendly"] },
      { name: "Calangute Beach", slug: "calangute-beach", stateId: stateMap["goa"], cityId: cityMap["panaji"], category: "nature", featured: false, images: ["https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800"], description: "Calangute is Goa's largest beach, known as the Queen of Beaches. Popular for water sports, sunbathing, and vibrant beach shacks.", bestTime: "November to February", fees: "Free", timings: "Open 24 hours", mapLink: "https://maps.google.com/?q=Calangute+Beach+Goa", nearbyAttractions: ["Baga Beach", "Fort Aguada", "Anjuna Flea Market"], tips: ["Avoid monsoon season for beach activities", "Try water sports like parasailing and jet skiing"], tags: ["popular", "adventure", "free-entry"] },
      { name: "City Palace Udaipur", slug: "city-palace-udaipur", stateId: stateMap["rajasthan"], cityId: cityMap["udaipur"], category: "heritage", featured: false, images: ["https://images.unsplash.com/photo-1602508451748-cb083ac3f5d4?w=800"], description: "The City Palace of Udaipur is a majestic complex of palaces built over 400 years by successive Mewar rulers, overlooking Lake Pichola.", history: "Construction began in 1559 by Maharana Udai Singh II. The palace blends Rajasthani and Mughal architectural styles.", bestTime: "September to March", fees: "₹300 (Indians), ₹700 (Foreigners)", timings: "9:30 AM – 5:30 PM", mapLink: "https://maps.google.com/?q=City+Palace+Udaipur", nearbyAttractions: ["Lake Pichola", "Jag Mandir", "Saheliyon Ki Bari"], tips: ["Book a sunset boat ride on Lake Pichola", "Audio guide available for detailed history"], tags: ["heritage", "popular"] },
      { name: "Dal Lake", slug: "dal-lake", stateId: stateMap["jammu-kashmir"], cityId: cityMap["srinagar"], category: "nature", featured: false, images: ["https://images.unsplash.com/photo-1597074866923-dc0589150a32?w=800"], description: "Dal Lake is Srinagar's crown jewel — a stunning lake surrounded by mountains, famous for its ornate houseboats and shikara rides.", bestTime: "April to October", fees: "Shikara ride from ₹500", timings: "Open 24 hours", mapLink: "https://maps.google.com/?q=Dal+Lake+Srinagar", nearbyAttractions: ["Mughal Gardens", "Shankaracharya Temple", "Nishat Bagh"], tips: ["Stay in a houseboat for an unforgettable experience", "Visit the floating vegetable market at dawn"], tags: ["nature", "popular"] },
      { name: "Meenakshi Temple", slug: "meenakshi-temple", stateId: stateMap["tamil-nadu"], cityId: cityMap["chennai"], category: "religious", featured: false, images: ["https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800"], description: "The Meenakshi Amman Temple in Madurai is a historic Hindu temple with stunning Dravidian architecture, featuring 14 colorful gopurams covered in thousands of sculptures.", history: "The temple dates back to the 6th century BCE and was rebuilt in the 17th century by Thirumalai Nayak.", bestTime: "October to March", fees: "Free (Camera ₹50)", timings: "5:00 AM – 12:30 PM, 4:00 PM – 10:00 PM", mapLink: "https://maps.google.com/?q=Meenakshi+Temple+Madurai", nearbyAttractions: ["Thirumalai Nayak Palace", "Gandhi Memorial Museum"], tips: ["Dress modestly and remove shoes before entering", "Explore the Hall of Thousand Pillars"], tags: ["religious", "popular", "free-entry"] },
    ];
    await TouristPlace.insertMany(placesData);

    return NextResponse.json({ message: "Database seeded successfully!", stats: { states: statesData.length, cities: citiesData.length, places: placesData.length } }, { status: 201 });
  } catch (error) {
    console.error("Seed error:", error);
    return NextResponse.json({ error: "Failed to seed database" }, { status: 500 });
  }
}
